#pragma once

enum class Language
{
    System = 0,
    English = 1,
    Chinese = 2,
};

enum StrId
{
    STR_NONE = -1,
    STR_APP_TITLE = 0,
    STR_GROUP_EDITOR,
    STR_GROUP_ZONE_BEHAVIOR,
    STR_GROUP_ZONE_APPEARANCE,
    STR_GROUP_WINDOW_BEHAVIOR,
    STR_GROUP_WINDOW_SWITCHING,
    STR_GROUP_MONITOR_ROTATION,
    STR_GROUP_OVERRIDE_SNAP,
    STR_GROUP_QUICK_SWITCH,
    STR_GROUP_EXCLUDED,
    STR_GROUP_APP,

    STR_ACTIVATION_SHORTCUT,
    STR_LAUNCH_EDITOR_DISPLAY,
    STR_OPT_ACTIVE_FOCUS,
    STR_OPT_MOUSE_POINTER,
    STR_SHIFT_DRAG,
    STR_MOUSE_SWITCH,
    STR_MIDDLE_CLICK_SPAN,
    STR_SHOW_ALL_MONITORS,
    STR_SPAN_MONITORS,
    STR_OVERLAP,
    STR_OVERLAP_SMALLEST,
    STR_OVERLAP_LARGEST,
    STR_OVERLAP_POSITIONAL,
    STR_OVERLAP_CLOSEST,
    STR_COLORS,
    STR_COLORS_CUSTOM,
    STR_COLORS_SYSTEM,
    STR_SHOW_ZONE_NUMBER,
    STR_OPACITY,
    STR_HIGHLIGHT_COLOR,
    STR_INACTIVE_COLOR,
    STR_BORDER_COLOR,
    STR_NUMBER_COLOR,
    STR_KEEP_ON_RESOLUTION_CHANGE,
    STR_MATCH_ON_LAYOUT_CHANGE,
    STR_LAST_KNOWN_ZONE,
    STR_ACTIVE_MONITOR_EXPERIMENTAL,
    STR_RESTORE_SIZE,
    STR_TRANSPARENT_DRAG,
    STR_CHILD_SNAP,
    STR_DISABLE_ROUND_CORNERS,
    STR_ENABLE_WINDOW_SWITCHING,
    STR_NEXT_WINDOW,
    STR_PREVIOUS_WINDOW,
    STR_ENABLE_ROTATION,
    STR_ROTATION_SHORTCUT,
    STR_OVERRIDE_SNAP,
    STR_MOVE_BASED_ON,
    STR_OPT_ZONE_INDEX,
    STR_OPT_RELATIVE_POSITION,
    STR_MOVE_ACROSS_MONITORS,
    STR_ENABLE_QUICK_SWITCH,
    STR_FLASH_ON_SWITCH,
    STR_EXCLUDED_DESCRIPTION,

    STR_THEME,
    STR_THEME_SYSTEM,
    STR_THEME_LIGHT,
    STR_THEME_DARK,
    STR_LANGUAGE,
    STR_LANGUAGE_SYSTEM,
    STR_LANGUAGE_ENGLISH,
    STR_LANGUAGE_CHINESE,
    STR_AUTOSTART,
    STR_TRAY_EXIT,
    STR_TRAY_SETTINGS,
    STR_TRAY_EDIT_LAYOUTS,

    STR_EDITOR_TITLE,
    STR_TEMPLATES,
    STR_CUSTOM_LAYOUTS,
    STR_ZONE_COUNT,
    STR_SPACING,
    STR_SHOW_SPACING,
    STR_APPLY,
    STR_APPLIED,
    STR_TEMPLATE_BLANK,
    STR_TEMPLATE_FOCUS,
    STR_TEMPLATE_COLUMNS,
    STR_TEMPLATE_ROWS,
    STR_TEMPLATE_GRID,
    STR_TEMPLATE_PRIORITY_GRID,

    STR_NEW_LAYOUT,
    STR_EDIT_GRID,
    STR_NEW_CANVAS,
    STR_EDIT_CANVAS,
    STR_ADD_ZONE,
    STR_DELETE_ZONE,
    STR_CANVAS_HINT,
    STR_SPLIT_LR,
    STR_SPLIT_TB,
    STR_MERGE_LEFT,
    STR_MERGE_UP,
    STR_MERGE_RIGHT,
    STR_MERGE_DOWN,
    STR_GRID_ROWS,
    STR_GRID_COLS,
    STR_LAYOUT_NAME,
    STR_SAVE_LAYOUT,
    STR_CANCEL,
    STR_GRID_HINT,
    STR_QUICK_SWITCH,
    STR_QUICK_SWITCH_HINT,
    STR_SET_DEFAULT_HORIZONTAL,
    STR_SET_DEFAULT_VERTICAL,
    STR_HOTKEY_CAPTURE,

    STR_COUNT
};

namespace Loc
{
    // Resolves Language::System against the user's UI locale and caches the resulting table.
    void SetLanguage(Language language);
    Language RequestedLanguage();

    // Which table the above resolved to; typography follows it, not the OS locale.
    bool UsesChinese();

    const wchar_t* T(StrId id);
}
